/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentHealthRouteImport } from './routes/student-health'
import { Route as SpecialGameRouteImport } from './routes/special-game'
import { Route as SmartBoardRouteImport } from './routes/smart-board'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PdfViewerRouteImport } from './routes/pdf-viewer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveClassRouteImport } from './routes/live-class'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ClassmatesRouteImport } from './routes/classmates'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BaniRouteImport } from './routes/bani'
import { Route as BangladeshMapRouteImport } from './routes/bangladesh-map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as SchoolsSchoolIdRouteImport } from './routes/schools.$schoolId'
import { Route as ApiCloudinaryUploadRouteImport } from './routes/api/cloudinary-upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHealthRoute = StudentHealthRouteImport.update({
  id: '/student-health',
  path: '/student-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialGameRoute = SpecialGameRouteImport.update({
  id: '/special-game',
  path: '/special-game',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartBoardRoute = SmartBoardRouteImport.update({
  id: '/smart-board',
  path: '/smart-board',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfViewerRoute = PdfViewerRouteImport.update({
  id: '/pdf-viewer',
  path: '/pdf-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassRoute = LiveClassRouteImport.update({
  id: '/live-class',
  path: '/live-class',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassmatesRoute = ClassmatesRouteImport.update({
  id: '/classmates',
  path: '/classmates',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BaniRoute = BaniRouteImport.update({
  id: '/bani',
  path: '/bani',
  getParentRoute: () => rootRouteImport,
} as any)
const BangladeshMapRoute = BangladeshMapRouteImport.update({
  id: '/bangladesh-map',
  path: '/bangladesh-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const SchoolsSchoolIdRoute = SchoolsSchoolIdRouteImport.update({
  id: '/$schoolId',
  path: '/$schoolId',
  getParentRoute: () => SchoolsRoute,
} as any)
const ApiCloudinaryUploadRoute = ApiCloudinaryUploadRouteImport.update({
  id: '/api/cloudinary-upload',
  path: '/api/cloudinary-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/books': typeof BooksRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quiz': typeof QuizRoute
  '/quizzes': typeof QuizzesRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/smart-board': typeof SmartBoardRoute
  '/special-game': typeof SpecialGameRoute
  '/student-health': typeof StudentHealthRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/books': typeof BooksRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quiz': typeof QuizRoute
  '/quizzes': typeof QuizzesRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/smart-board': typeof SmartBoardRoute
  '/special-game': typeof SpecialGameRoute
  '/student-health': typeof StudentHealthRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bangladesh-map': typeof BangladeshMapRoute
  '/bani': typeof BaniRoute
  '/books': typeof BooksRoute
  '/certificates': typeof CertificatesRoute
  '/classmates': typeof ClassmatesRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/ecosystem': typeof EcosystemRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/live-class': typeof LiveClassRoute
  '/login': typeof LoginRoute
  '/pdf-viewer': typeof PdfViewerRoute
  '/quiz': typeof QuizRoute
  '/quizzes': typeof QuizzesRoute
  '/school': typeof SchoolRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/smart-board': typeof SmartBoardRoute
  '/special-game': typeof SpecialGameRoute
  '/student-health': typeof StudentHealthRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/cloudinary-upload': typeof ApiCloudinaryUploadRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/books'
    | '/certificates'
    | '/classmates'
    | '/competitions'
    | '/dashboard'
    | '/ecosystem'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quiz'
    | '/quizzes'
    | '/school'
    | '/schools'
    | '/smart-board'
    | '/special-game'
    | '/student-health'
    | '/students'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/subjects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/books'
    | '/certificates'
    | '/classmates'
    | '/competitions'
    | '/dashboard'
    | '/ecosystem'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quiz'
    | '/quizzes'
    | '/school'
    | '/schools'
    | '/smart-board'
    | '/special-game'
    | '/student-health'
    | '/students'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/subjects/$slug'
  id:
    | '__root__'
    | '/'
    | '/bangladesh-map'
    | '/bani'
    | '/books'
    | '/certificates'
    | '/classmates'
    | '/competitions'
    | '/dashboard'
    | '/ecosystem'
    | '/games'
    | '/leaderboard'
    | '/library'
    | '/live-class'
    | '/login'
    | '/pdf-viewer'
    | '/quiz'
    | '/quizzes'
    | '/school'
    | '/schools'
    | '/smart-board'
    | '/special-game'
    | '/student-health'
    | '/students'
    | '/subjects'
    | '/api/chat'
    | '/api/cloudinary-upload'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/subjects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangladeshMapRoute: typeof BangladeshMapRoute
  BaniRoute: typeof BaniRoute
  BooksRoute: typeof BooksRoute
  CertificatesRoute: typeof CertificatesRoute
  ClassmatesRoute: typeof ClassmatesRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DashboardRoute: typeof DashboardRoute
  EcosystemRoute: typeof EcosystemRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  LiveClassRoute: typeof LiveClassRoute
  LoginRoute: typeof LoginRoute
  PdfViewerRoute: typeof PdfViewerRoute
  QuizRoute: typeof QuizRoute
  QuizzesRoute: typeof QuizzesRoute
  SchoolRoute: typeof SchoolRoute
  SchoolsRoute: typeof SchoolsRouteWithChildren
  SmartBoardRoute: typeof SmartBoardRoute
  SpecialGameRoute: typeof SpecialGameRoute
  StudentHealthRoute: typeof StudentHealthRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SubjectsRoute: typeof SubjectsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiCloudinaryUploadRoute: typeof ApiCloudinaryUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-health': {
      id: '/student-health'
      path: '/student-health'
      fullPath: '/student-health'
      preLoaderRoute: typeof StudentHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-game': {
      id: '/special-game'
      path: '/special-game'
      fullPath: '/special-game'
      preLoaderRoute: typeof SpecialGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-board': {
      id: '/smart-board'
      path: '/smart-board'
      fullPath: '/smart-board'
      preLoaderRoute: typeof SmartBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-viewer': {
      id: '/pdf-viewer'
      path: '/pdf-viewer'
      fullPath: '/pdf-viewer'
      preLoaderRoute: typeof PdfViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-class': {
      id: '/live-class'
      path: '/live-class'
      fullPath: '/live-class'
      preLoaderRoute: typeof LiveClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classmates': {
      id: '/classmates'
      path: '/classmates'
      fullPath: '/classmates'
      preLoaderRoute: typeof ClassmatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bani': {
      id: '/bani'
      path: '/bani'
      fullPath: '/bani'
      preLoaderRoute: typeof BaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bangladesh-map': {
      id: '/bangladesh-map'
      path: '/bangladesh-map'
      fullPath: '/bangladesh-map'
      preLoaderRoute: typeof BangladeshMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/schools/$schoolId': {
      id: '/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof SchoolsSchoolIdRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/api/cloudinary-upload': {
      id: '/api/cloudinary-upload'
      path: '/api/cloudinary-upload'
      fullPath: '/api/cloudinary-upload'
      preLoaderRoute: typeof ApiCloudinaryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchoolsRouteChildren {
  SchoolsSchoolIdRoute: typeof SchoolsSchoolIdRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsSchoolIdRoute: SchoolsSchoolIdRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangladeshMapRoute: BangladeshMapRoute,
  BaniRoute: BaniRoute,
  BooksRoute: BooksRoute,
  CertificatesRoute: CertificatesRoute,
  ClassmatesRoute: ClassmatesRoute,
  CompetitionsRoute: CompetitionsRoute,
  DashboardRoute: DashboardRoute,
  EcosystemRoute: EcosystemRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  LiveClassRoute: LiveClassRoute,
  LoginRoute: LoginRoute,
  PdfViewerRoute: PdfViewerRoute,
  QuizRoute: QuizRoute,
  QuizzesRoute: QuizzesRoute,
  SchoolRoute: SchoolRoute,
  SchoolsRoute: SchoolsRouteWithChildren,
  SmartBoardRoute: SmartBoardRoute,
  SpecialGameRoute: SpecialGameRoute,
  StudentHealthRoute: StudentHealthRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SubjectsRoute: SubjectsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiCloudinaryUploadRoute: ApiCloudinaryUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
